[package]
authors = ['Manta Network']
edition = "2021"
name = "manta-farming-rpc-runtime-api"
version = "4.0.3"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }

manta-primitives = { path = '../../../../primitives/manta', default-features = false }

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-api/std",
  "manta-primitives/std",
]
