[workspace]
members = [
  "node",
  "pallets/*",
  "pallets/farming/rpc",
  "primitives/*",
  "runtime/*",
]
resolver = "2"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true
strip = "symbols"

[profile.release]
panic = "unwind"

[profile.test]
debug = true
