
[workspace]
resolver = "2"
members = [
	'node',
	'pallets/*',
	'runtime/manta',
	'runtime/calamari',
	'runtime/dolphin',
	'runtime/common',
	'primitives',
	'nimbus-primitives',
	'nimbus-consensus',
]

[profile.production]
inherits = "release"
codegen-units = 1
lto = true

[profile.release]
panic = "unwind"

[profile.test]
debug = true
