[package]
authors = ['Manta Network']
edition = "2021"
homepage = 'https://manta.network'
license = 'GPL-3.0'
name = "runtime-common"
repository = 'https://github.com/Manta-Network/Manta/'
version = '3.2.1'

[dependencies]
# Substrate dependencies
frame-support = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24", default-features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24", default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24", default-features = false }

# Self dependencies
manta-primitives = { path = '../../primitives/manta', default-features = false }

[dev-dependencies]
# 3rd dependencies
codec = { package = "parity-scale-codec", version = "3.1.2" }
scale-info = { version = "2.1.2", features = ["derive"] }

# Substrate dependencies
frame-system = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
pallet-assets = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
pallet-utility = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }
sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.24" }

# Polkadot dependencies
pallet-xcm = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
polkadot-core-primitives = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
polkadot-runtime-parachains = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
xcm = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
xcm-builder = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
xcm-executor = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }
xcm-simulator = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.24" }

# Cumulus dependencies
cumulus-pallet-dmp-queue = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.24" }
cumulus-pallet-parachain-system = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.24" }
cumulus-pallet-xcm = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.24" }
cumulus-pallet-xcmp-queue = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.24" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v0.9.24" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v0.9.24" }
parachain-info = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.24" }

# Orml dependencies
orml-traits = { git = "https://github.com/manta-network/open-runtime-module-library.git", rev = "cc26ffa" }
orml-xtokens = { git = "https://github.com/manta-network/open-runtime-module-library.git", rev = "cc26ffa" }

# Self dependencies
pallet-asset-manager = { path = '../../pallets/asset-manager' }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "manta-primitives/std",
  "pallet-transaction-payment/std",
  "sp-runtime/std",
]
