[package]
authors = ['Manta Network']
name = "runtime-common"
version = '3.1.5'
edition = "2021"
homepage = 'https://manta.network'
license = 'GPL-3.0'
repository = 'https://github.com/Manta-Network/Manta/'

[dependencies]

[dev-dependencies]

# 3rd dependencies
codec = { package = "parity-scale-codec", version = "2.3.1" }
scale-info = { version = "1.0", features = [ "derive" ] }

# Substrate dependencies
frame-support = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
frame-system = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
pallet-utility = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }
pallet-assets = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.16" }

# Polkadot dependencies
polkadot-core-primitives = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16" }
polkadot-runtime-parachains = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16" }
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16" }
pallet-xcm = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16" }
xcm = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16" }
xcm-builder = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16"}
xcm-executor = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16"}
xcm-simulator = { git = 'https://github.com/paritytech/polkadot.git', branch = "release-v0.9.16"}

# Cumulus dependencies
parachain-info = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.16" }
cumulus-pallet-xcm = { git = 'https://github.com/paritytech/cumulus.git', branch = "polkadot-v0.9.16" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v0.9.16" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v0.9.16" }

# Orml dependencies
orml-xtokens = { git = "https://github.com/manta-network/open-runtime-module-library.git", rev="4a66b29" }

# Self dependencies
pallet-asset-manager = { path = '../../pallets/asset-manager' }
manta-primitives = { path = '../../primitives' }

[features]
default = ["std"]
std = []
