[package]
authors = ['Manta Network']
edition = '2021'
homepage = 'https://manta.network'
license = 'GPL-3.0'
name = 'manta-runtime'
repository = 'https://github.com/Manta-Network/Manta/'
version = '4.0.2'

[dependencies]
codec = { package = "parity-scale-codec", version = '3.1.2', default-features = false, features = ["derive", "max-encoded-len"] }
hex-literal = { version = '0.3.4', optional = true }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.140", features = ['derive'], optional = true }
smallvec = "1.8.0"

# Substrate primitives
sp-api = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-application-crypto = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-arithmetic = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-io = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-offchain = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-session = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-std = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
sp-version = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }

# Substrate frames
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', default-features = false, optional = true, branch = "polkadot-v0.9.37" }
frame-executive = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
frame-support = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
frame-system = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate.git', default-features = false, optional = true, branch = "polkadot-v0.9.37" }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
frame-try-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true, branch = "polkadot-v0.9.37" }

# Substrate pallets
pallet-aura = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-authorship = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-multisig = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-preimage = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-session = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-sudo = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }
pallet-utility = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.37" }

# Cumulus dependencies
cumulus-pallet-dmp-queue = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }
cumulus-pallet-parachain-system = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }
cumulus-pallet-session-benchmarking = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, optional = true, branch = "polkadot-v0.9.37" }
cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }
cumulus-primitives-timestamp = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }
cumulus-primitives-utility = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }
parachain-info = { git = 'https://github.com/paritytech/cumulus.git', default-features = false, branch = "polkadot-v0.9.37" }

# Nimbus Dependencies
nimbus-primitives = { git = "https://github.com/manta-network/nimbus.git", branch = "polkadot-v0.9.37", default-features = false }
pallet-aura-style-filter = { git = "https://github.com/manta-network/nimbus.git", branch = "polkadot-v0.9.37", default-features = false }
pallet-author-inherent = { git = "https://github.com/manta-network/nimbus.git", branch = "polkadot-v0.9.37", default-features = false }

# Polkadot dependencies
pallet-xcm = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }
polkadot-primitives = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }
xcm = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }
xcm-builder = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }
xcm-executor = { git = 'https://github.com/paritytech/polkadot.git', default-features = false, branch = "release-v0.9.37" }

# Self dependencies
manta-collator-selection = { path = '../../pallets/collator-selection', default-features = false }
manta-primitives = { path = '../../primitives/manta', default-features = false }
pallet-parachain-staking = { path = '../../pallets/parachain-staking', default-features = false }
runtime-common = { path = '../common', default-features = false }
session-key-primitives = { path = '../../primitives/session-keys', default-features = false }

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.37" }

[features]
default = ['std']
runtime-benchmarks = [
  'cumulus-pallet-session-benchmarking/runtime-benchmarks',
  'hex-literal',
  'sp-runtime/runtime-benchmarks',
  'frame-benchmarking/runtime-benchmarks',
  'frame-system-benchmarking/runtime-benchmarks',
  'frame-support/runtime-benchmarks',
  'frame-system/runtime-benchmarks',
  'manta-collator-selection/runtime-benchmarks',
  'nimbus-primitives/runtime-benchmarks',
  'pallet-author-inherent/runtime-benchmarks',
  'pallet-balances/runtime-benchmarks',
  'pallet-multisig/runtime-benchmarks',
  'pallet-utility/runtime-benchmarks',
  'pallet-timestamp/runtime-benchmarks',
  'pallet-parachain-staking/runtime-benchmarks',
  'pallet-preimage/runtime-benchmarks',
  'cumulus-pallet-parachain-system/runtime-benchmarks',
]
try-runtime = [
  'frame-try-runtime',
  'frame-executive/try-runtime',
  'frame-system/try-runtime',
  "frame-support/try-runtime",
  'pallet-authorship/try-runtime',
  'pallet-balances/try-runtime',
  'pallet-parachain-staking/try-runtime',
  'pallet-preimage/try-runtime',
  'pallet-multisig/try-runtime',
  'pallet-session/try-runtime',
  'pallet-timestamp/try-runtime',
  'pallet-transaction-payment/try-runtime',
  'pallet-utility/try-runtime',
  'runtime-common/try-runtime',
  "cumulus-pallet-parachain-system/try-runtime",
  "parachain-info/try-runtime",
  'pallet-aura/try-runtime',
  'pallet-xcm/try-runtime',
  "cumulus-pallet-dmp-queue/try-runtime",
  'pallet-aura-style-filter/try-runtime',
  'manta-collator-selection/try-runtime',
  'pallet-author-inherent/try-runtime',
  'pallet-sudo/try-runtime',
]
# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []
std = [
  'codec/std',
  'serde',
  'sp-consensus-aura/std',
  'pallet-aura/std',
  'sp-api/std',
  'sp-std/std',
  'sp-io/std',
  'sp-core/std',
  'sp-runtime/std',
  'sp-version/std',
  'sp-offchain/std',
  'sp-session/std',
  'sp-block-builder/std',
  'sp-transaction-pool/std',
  'sp-inherents/std',
  'frame-support/std',
  'frame-executive/std',
  'frame-system/std',
  'frame-system-rpc-runtime-api/std',
  'frame-try-runtime/std',
  "frame-system-benchmarking/std",
  'pallet-authorship/std',
  'pallet-balances/std',
  'pallet-multisig/std',
  'pallet-parachain-staking/std',
  'pallet-preimage/std',
  'pallet-utility/std',
  'pallet-transaction-payment-rpc-runtime-api/std',
  'pallet-timestamp/std',
  'pallet-session/std',
  'pallet-sudo/std',
  'pallet-transaction-payment/std',
  'manta-primitives/std',
  'runtime-common/std',
  'parachain-info/std',
  'cumulus-pallet-parachain-system/std',
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "cumulus-pallet-dmp-queue/std",
  "pallet-author-inherent/std",
  "pallet-aura-style-filter/std",
  'session-key-primitives/std',
  'polkadot-primitives/std',
  'manta-collator-selection/std',
  'xcm/std',
  'pallet-xcm/std',
  'xcm-executor/std',
  'xcm-builder/std',
]
