name: Changelog Verification
on:
  push:
jobs:
  verify_changelog:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: manta
    - name: Save Dev Local CHANGELOG for diff
      run: |
        cd manta
        sudo cp CHANGELOG.md CHANGELOG_ORIGIN.md
    - name: get Changelog Generator
      uses: actions/checkout@v2
      with:
        repository: Manta-Network/Dev-Tools
        path: dev-tools
    - name: Generate workflow Changelog
      run: |
        cd dev-tools/changelog-generator
        cargo b -r
        cargo run -- -u ${{ github.actor }} ${{ github.token }} -r ${{ github.workspace }}/manta
        
