---

# yamllint disable rule:line-length

name: publish calamari parachain container
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [manta]
  push:
    branches: [ghzlatarev/docker-debug]
jobs:
  docker-hub-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        runtime:
          -
            name: calamari
          -
            name: manta
    steps:
      -
        uses: docker/setup-buildx-action@v1

# yamllint enable rule:line-length
