---
# yamllint disable rule:line-length

# This workflow checks whether `transaction_version` should be updated.

name: Transaction Version Update Check
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reference_url:
        description: The WebSocket url of the reference node
        default: wss://ws.calamari.systems/
        required: true
      chain:
        description: The name of the chain under test. Usually, you would pass a local chain
        default: calamari-local
        required: true

env:
  AWS_REGION: us-east-1
  AWS_INSTANCE_TYPE: c5a.8xlarge
  AWS_INSTANCE_ROOT_VOLUME_SIZE: 32
  AWS_IMAGE_SEARCH_PATTERN: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
  AWS_IMAGE_SEARCH_OWNERS: '["099720109477"]'  # canonical
  CHAIN: ${{github.event.inputs.chain}}
  REF_URL: ${{github.event.inputs.reference_url}}

jobs:

  start-checks:
    runs-on: ubuntu-20.04
    outputs:
      runner-label: ${{ steps.start-self-hosted-runner.outputs.runner-label }}
      aws-region: ${{ steps.start-self-hosted-runner.outputs.aws-region }}
      aws-instance-id: ${{ steps.start-self-hosted-runner.outputs.aws-instance-id }}
    steps:
      -
        id: start-self-hosted-runner
        uses: audacious-network/aws-github-runner@v1.0.33
        with:
          mode: start
          github-token: ${{ secrets.GH_SHR_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-instance-type: ${{ env.AWS_INSTANCE_TYPE }}
          aws-instance-root-volume-size: ${{ env.AWS_INSTANCE_ROOT_VOLUME_SIZE }}
          aws-image-search-pattern: ${{ env.AWS_IMAGE_SEARCH_PATTERN }}
          aws-image-search-owners: ${{ env.AWS_IMAGE_SEARCH_OWNERS }}  # canonical
      - name: Download
        run: |
          wget https://github.com/Manta-Network/Manta/releases/download/v3.1.5/manta
          chmod +x manta
      - name: Start local node
        run: |
          echo Running on $CHAIN
          ./manta --chain=$CHAIN -- --chain kusama &
      - name: Prepare output
        run: |
          VERSION=$(./target/debug/manta --version)
          echo "Metadata comparison:" >> output.txt
          echo "Date: $(date)" >> output.txt
          echo "Reference: $REF_URL" >> output.txt
          echo "Target version: $VERSION" >> output.txt
          echo "Chain: $CHAIN" >> output.txt
          echo "----------------------------------------------------------------------" >> output.txt
      - name: Pull polkadot-js-tools image
        run: docker pull jacogr/polkadot-js-tools
      - name: Compare the metadata
        run: |
          CMD="docker run --pull always --network host jacogr/polkadot-js-tools metadata $REF_URL ws://localhost:9944"
          echo -e "Running:\n$CMD"
          $CMD >> output.txt
          sed -z -i 's/\n\n/\n/g' output.txt
          cat output.txt | egrep -n -i ''
          chmod +x ./scripts/github/extrinsic-ordering-filter.sh
          SUMMARY=$(./scripts/github/extrinsic-ordering-filter.sh output.txt)
          echo -e $SUMMARY
          echo -e $SUMMARY >> output.txt
      - name: Show result
        run: |
          cat output.txt
      - name: Stop our local node
        run: pkill manta

      - name: Save output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CHAIN }}
          path: |
            output.txt

  stop-checks:
    needs:
      - start-checks
    runs-on: ubuntu-20.04
    if: ${{ always() }}
    steps:
      -
        uses: audacious-network/aws-github-runner@v1.0.33
        with:
          mode: stop
          github-token: ${{ secrets.GH_SHR_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ needs.start-checks.outputs.aws-region }}
          runner-label: ${{ needs.start-checks.outputs.runner-label }}
          aws-instance-id: ${{ needs.start-checks.outputs.aws-instance-id }}
