---

# yamllint disable rule:line-length

# The try-runtime tool expects your local chain's runtime version to match
# the version of the chain that you're testing against. In this case Calamari mainnet.
# That's why this CI workflow has a manual trigger.
name: Execute try-runtime with latest Calamari mainnet state

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  build-node:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: install sccache

        env:
          SCCACHE_RELEASE_URL: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: v0.2.15
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$SCCACHE_RELEASE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          chmod +x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      -
        name: cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-
      -
        name: cache sccache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: /home/runner/.cache/sccache
          key: sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            sccache-
      -
        name: start sccache server
        run: sccache --start-server
      -
        name: init
        run: |
          curl -s https://sh.rustup.rs -sSf | sh -s -- -y
          source ${HOME}/.cargo/env
          rustup toolchain install stable
          rustup toolchain install nightly
          rustup default stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force
          rustup update
      -
        name: build
        env:
          RUST_BACKTRACE: full
          RUSTC_WRAPPER: sccache
          SCCACHE_CACHE_SIZE: 2G
          SCCACHE_DIR: /home/runner/.cache/sccache
          CARGO_TERM_COLOR: always
        run: |
          source ${HOME}/.cargo/env
          cargo build --profile release --verbose --features=try-runtime
      -
        name: stop sccache server
        run: sccache --stop-server || true
      -
        run: |
          mv target/release/manta $HOME/.local/bin/
          chmod +x $HOME/.local/bin/manta
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      -
        uses: actions/checkout@v2
        with:
          repository: Manta-Network/Dev-Tools
          path: dev-tools-calamari
      -
        name: execute try-runtime
        run: |
          cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
          yarn install
          yarn build
          latest_hash=$(node get-latest-finalized-header-hash --address=wss://ws.calamari.systems:443)
          $HOME/.local/bin/manta try-runtime --chain calamari-dev on-runtime-upgrade live --at $latest_hash --uri wss://ws.calamari.systems:443

# yamllint enable rule:line-length
