---

# yamllint disable rule:line-length

# The try-runtime tool expects your local chain's runtime version to match
# the version of the chain that you're testing against. In this case Calamari mainnet.
# That's why this CI workflow has a manual trigger.
name: Execute try-runtime with latest Calamari mainnet state

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:

  run-try-runtime:
    name: try-runtime
    runs-on: ubuntu-20.04
    steps:
      -
        run: |
          wget https://github.com/Manta-Network/Manta/releases/download/v3.1.5/manta
          mkdir -p $HOME/.local/bin
          mv manta $HOME/.local/bin/
          chmod +x $HOME/.local/bin/manta
          echo "$HOME/.local/bin" >> $GITHUB_PATH
 -
        uses: actions/checkout@v2
      -
        name: init
        run: |
          curl -s https://sh.rustup.rs -sSf | sh -s -- -y
          source ${HOME}/.cargo/env
          rustup toolchain install stable
          rustup toolchain install nightly
          rustup default stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup update
      -
        name: build
        run: |
          source ${HOME}/.cargo/env
          cargo build --profile debug --verbose --features=try-runtime
          mkdir -p $HOME/.local/bin
          mv manta $HOME/.local/bin/
          chmod +x $HOME/.local/bin/manta
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      -
        name: move bin
        run: |
          mkdir -p $HOME/.local/bin
          mv target/debug/manta $HOME/.local/bin/
          chmod +x $HOME/.local/bin/manta
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      -
        uses: actions/checkout@v2
        with:
          repository: Manta-Network/Dev-Tools
          path: dev-tools-calamari
      -
        name: execute try-runtime
        run: |
          cd ${{ github.workspace }}/dev-tools-calamari/check-finalized-block
          yarn install
          yarn
          latest_hash=$(node get-latest-finalized-header-hash --address=wss://ws.calamari.systems:443)
          $HOME/.local/bin/manta try-runtime --chain calamari-dev on-runtime-upgrade live --at $latest_hash --uri wss://ws.calamari.systems:443

# yamllint enable rule:line-length
